vpc_cidr_block                = "10.0.0.0/16"
enable_dns_support            = true
enable_dns_hostnames          = true
igw_name                      = "TA-ig"
nat_eip_vpc                   = true
public_subnet_cidr_blocks     = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidr_blocks    = ["10.0.3.0/24", "10.0.4.0/24"]
multi_az                      = true
availability_zones            = ["us-east-1a", "us-east-1b"]
alb_sg_name                   = "ta_alb_sg"
ec2_sg_name                   = "ta_ec2_sg"
lb_name                       = "ta-alb"
target_group_name             = "ta-target-group"
web_instance_type             = "t2.micro"
db_subnet_group_name          = "ta-db-subnet-group"
db_instance_class             = "db.t3.micro"
db_name                       = "tadatabase"
db_username                   = "admin"
db_password                   = ""
rds_sg_name                   = "ta_rds_sg"
rds_sg_description            = "Allow traffic from EC2 instances to RDS"
rds_sg_ingress_port           = 3306
rds_sg_egress_cidr_blocks     = ["0.0.0.0/0"]
autoscaling_group_name        = "web"
launch_template_name          = "web-launch-config"
launch_template_image_id      = "ami-00beae93a2d981137"
launch_template_instance_type = "t2.micro"
launch_template_public_ip     = false